-- Create the storage schema if it doesn't exist
CREATE SCHEMA IF NOT EXISTS storage;

-- Create the http_request_queue table if it doesn't exist
CREATE TABLE IF NOT EXISTS storage.http_request_queue (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url text NOT NULL DEFAULT '',
    method text,
    headers jsonb,
    body text,
    timeout_milliseconds integer,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    status integer,
    response_body text,
    response_headers jsonb
);

-- Ensure proper indexes
CREATE INDEX IF NOT EXISTS http_request_queue_status_idx ON storage.http_request_queue (status);
CREATE INDEX IF NOT EXISTS http_request_queue_created_at_idx ON storage.http_request_queue (created_at);

-- Grant necessary permissions
GRANT ALL PRIVILEGES ON SCHEMA storage TO postgres, anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA storage TO postgres, anon, authenticated, service_role;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA storage TO postgres, anon, authenticated, service_role;
